sudo: true
dist: trusty

install:
  - sudo apt-get install python
  - sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install ffmpeg gstreamer0.10-ffmpeg

script:
  - python convert.py
